admin_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDAhLwOu11GmTZ1vOormmaygACw2bCQaj22kwFH05dNtLhJrGgzhiAJxmoKNje9+PFx1d8LHLL2ydycD2Tta+uIDSxzqHkH7yN2guYB0sebvKb3fkdV+SR7/UbwTC7BSLVol2Eu4twhPnhnrNOWcba89HIPytBJHm/JmaLUTfryD+QkxaRIKo/qUS7DwXTE1dGO5r+Hg4DN2fWOJQxkEiiuUrAS9d8RwXvktFgKDKCy7Gw0TcnyWccG4MTPMliY3QELDY0sMhuMIGnx8UGHD547AsxnJ8fEW6K+LzzjQIVRPCymDBIO1T8Ue/NEjrTpj8BANhxZlqq8UBG9bOQf3kGmOIlCOBz4lZQpi3ahKHbmHi5LojhiOlpeKJk+miHgEJ7lzFVesB7On7T2HB/D8BALvN3g2LPJP0oxYIEjvA0dd64+8jbyo59xGLQBvP9dxIAsJjoXdUAhMRBfww9XiIylz5fXCnDt4mvNiq//JqKidsDIeg/Y5Vs45JBa5PFi8Rc= shey@mercury"


# user keys:
users:
  shey:
    ssh_key:
      - "{{ admin_key }}"
  oauth2:
    ssh_key:
      - "{{ admin_key }}"

# oauth2 proxy related
github_client_id: "c542e55d69e2c785a3a4"
github_client_secret : "{{ vault_github_client_secret }}"
oauth2_proxy_secret_cookie : "{{ vault_oauth2_proxy_secret_cookie }}"

# airbyte
airbyte_webapp_port: 8000

# certbot/nginx
admin_email: "shey@shey.ca"
server_name: "internal.shey.ca"
